export type ShortcutKind = "rdp" | "ssh";

export type ShortcutProfile = {
  id: string;
  name: string;
  kind: ShortcutKind;
  host: string;
  port?: number; // SSH only
  username?: string; // SSH only
  rdpUsername?: string; // RDP only
  rdpFullscreen?: boolean; // RDP only
  rdpAdmin?: boolean; // RDP only
  // WARNING: optional, plain-text; untuk latihan / non‑production saja.
  password?: string;
  note?: string;
  createdAt: string;
  updatedAt: string;
};

function safeFilePart(input: string) {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function buildBatFilename(p: ShortcutProfile) {
  const name = safeFilePart(p.name) || "shortcut";
  const host = safeFilePart(p.host) || "host";
  return `pam_${name}_${p.kind}_${host}.bat`;
}

export function buildBatScript(p: ShortcutProfile) {
  const host = (p.host || "").trim();
  const name = (p.name || "").trim();
  const now = new Date().toISOString();

  if (p.kind === "rdp") {
    const fullscreen = p.rdpFullscreen !== false;
    const admin = Boolean(p.rdpAdmin);
    const rdpUser = (p.rdpUsername || "").trim();
    const pwd = (p.password || "").trim();

    const mstscArgs = [
      "/v:%SERVER%",
      fullscreen ? "/f" : "",
      admin ? "/admin" : "",
    ]
      .filter(Boolean)
      .join(" ");

    // Jika tidak ada username atau password, pakai mode biasa (mstsc prompt password).
    if (!rdpUser || !pwd) {
      return [
        "@echo off",
        `:: Generated by PAM Shortcut Launcher (${now})`,
        `:: Name: ${name}`,
        `:: Kind: RDP`,
        `:: Host: ${host}`,
        rdpUser ? `:: Username: ${rdpUser}` : "",
        "",
        "setlocal",
        `set SERVER=${host}`,
        "echo Connecting ke: %SERVER%",
        `start "" mstsc ${mstscArgs} /prompt`,
        "endlocal",
        "",
      ].join("\r\n");
    }

    // Mode latihan: cred disimpan di profile & di .bat → auto login via cmdkey + mstsc.
    const safePwd = pwd.replace(/"/g, "");

    return [
      "@echo off",
      `:: Generated by PAM Shortcut Launcher (${now})`,
      `:: Name: ${name}`,
      `:: Kind: RDP`,
      `:: Host: ${host}`,
      rdpUser ? `:: Username: ${rdpUser}` : "",
      ":: WARNING: Password tersimpan di profile & file .bat (LATIHAN / NON‑PROD SAJA).",
      "",
      "setlocal",
      `set SERVER=${host}`,
      `set USERNAME=%COMPUTERNAME%\\${rdpUser}`,
      "echo Login sebagai: %USERNAME%",
      "echo Connecting ke: %SERVER%",
      `cmdkey /generic:TERMSRV/%SERVER% /user:%USERNAME% /pass:"${safePwd}"`,
      `mstsc ${mstscArgs}`,
      "endlocal",
      "",
    ].join("\r\n");
  }

  const port = Number.isFinite(p.port) && (p.port ?? 0) > 0 ? p.port : 22;
  const user = (p.username || "").trim();
  const target = user ? `${user}@${host}` : host;
  const pwd = (p.password || "").trim();

  // Jika ada username + password, gunakan plink (PuTTY) untuk auto-login.
  if (user && pwd) {
    return [
      "@echo off",
      `:: Generated by PAM Shortcut Launcher (${now})`,
      `:: Name: ${name}`,
      `:: Kind: SSH`,
      `:: Target: ${target}`,
      ":: WARNING: Password tersimpan di profile & file .bat (LATIHAN / NON‑PROD SAJA).",
      "",
      "setlocal",
      `set HOST=${host}`,
      `set PORT=${port}`,
      `set USER=${user}`,
      `set PASS=${pwd}`,
      "echo Connecting SSH ke: %USER%@%HOST%:%PORT%",
      ":: Cek apakah plink (PuTTY) sudah terpasang",
      "where plink >nul 2>&1",
      "if %ERRORLEVEL% NEQ 0 (",
      "  echo plink.exe belum ditemukan. Menginstall PuTTY via winget...",
      "  winget install --id PuTTY.PuTTY -e --source winget",
      "  echo Selesai install PuTTY. Melanjutkan koneksi...",
      ")",
      "plink -ssh -P %PORT% -l %USER% -pw \"%PASS%\" %HOST%",
      "endlocal",
      "",
    ].join("\r\n");
  }

  // Fallback: ssh.exe standar, user akan diminta memasukkan password manual.
  return [
    "@echo off",
    `:: Generated by PAM Shortcut Launcher (${now})`,
    `:: Name: ${name}`,
    `:: Kind: SSH`,
    `:: Target: ${target}`,
    "",
    "setlocal",
    `ssh -p ${port} ${target}`,
    "endlocal",
    "",
    "pause",
    "",
  ].join("\r\n");
}

export function buildRdpFilename(p: ShortcutProfile) {
  const name = safeFilePart(p.name) || "shortcut";
  const host = safeFilePart(p.host) || "host";
  return `pam_${name}_rdp_${host}.rdp`;
}

export function buildRdpFile(p: ShortcutProfile) {
  const host = (p.host || "").trim();
  const username = (p.rdpUsername || "").trim();

  // Intentionally no password storage.
  // RDP file format: key:type:value (s=string, i=integer)
  const lines = [
    `full address:s:${host}`,
    username ? `username:s:${username}` : "",
    `prompt for credentials:i:1`,
    `authentication level:i:2`,
    `enablecredsspsupport:i:1`,
    `redirectclipboard:i:1`,
    `redirectprinters:i:0`,
    `redirectcomports:i:0`,
    `redirectsmartcards:i:1`,
    `audiomode:i:0`,
    `session bpp:i:32`,
  ].filter(Boolean);

  return lines.join("\r\n") + "\r\n";
}

export function isValidProfile(p: ShortcutProfile) {
  if (!p.id) return false;
  if (!p.name.trim()) return false;
  if (!p.host.trim()) return false;
  if (p.kind === "ssh") {
    const port = p.port ?? 22;
    if (!Number.isFinite(port) || port <= 0 || port > 65535) return false;
  }
  return true;
}

export function defaultProfiles(): ShortcutProfile[] {
  const now = new Date().toISOString();
  return [
    {
      id: "rdp_source_control_10_70_12_250",
      name: "RDP - 10.70.12.250 (source-control)",
      kind: "rdp",
      host: "10.70.12.250",
      rdpUsername: "source-control",
      rdpFullscreen: true,
      rdpAdmin: false,
      note: "Saat download .bat, password akan diminta saat dijalankan (tidak disimpan).",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ssh_source_control_10_70_12_250",
      name: "SSH - 10.70.12.250 (source-control)",
      kind: "ssh",
      host: "10.70.12.250",
      port: 22,
      username: "source-control",
      note: "ssh.exe akan prompt password saat connect (tidak disimpan).",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "demo_rdp_jumpbox",
      name: "RDP - Jumpbox",
      kind: "rdp",
      host: "10.10.10.10",
      rdpFullscreen: true,
      rdpAdmin: false,
      note: "Contoh: akses RDP ke jumpbox internal",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "demo_ssh_linux",
      name: "SSH - Linux",
      kind: "ssh",
      host: "10.10.10.20",
      port: 22,
      username: "admin",
      note: "Contoh: login SSH pakai OpenSSH (ssh.exe)",
      createdAt: now,
      updatedAt: now,
    },
  ];
}


