param(
  [Parameter(Mandatory = $true)]
  [string]$BatPath,

  [Parameter(Mandatory = $true)]
  [string]$OutExe
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $BatPath)) {
  throw "BatPath not found: $BatPath"
}

$batFull = (Resolve-Path -LiteralPath $BatPath).Path
$exeFull = (Resolve-Path -LiteralPath (Split-Path -Parent $OutExe)).Path + "\" + (Split-Path -Leaf $OutExe)

if (-not (Get-Command Invoke-ps2exe -ErrorAction SilentlyContinue)) {
  throw "Invoke-ps2exe not found. Install first: Install-Module ps2exe -Scope CurrentUser -Force"
}

$content = Get-Content -LiteralPath $batFull -Raw

# Wrap batch content in a temporary .ps1 that writes a .bat and executes it.
$tmpDir = Join-Path $env:TEMP ("pam-shortcut_" + [Guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tmpDir | Out-Null

$wrapperPs1 = Join-Path $tmpDir "wrapper.ps1"
$embeddedBat = Join-Path $tmpDir "embedded.bat"

$ps = @"
`$ErrorActionPreference = 'Stop'
`$bat = @'
$content
'@
Set-Content -LiteralPath '$embeddedBat' -Value `$bat -Encoding ASCII
Start-Process -FilePath '$embeddedBat'
"@

Set-Content -LiteralPath $wrapperPs1 -Value $ps -Encoding UTF8

Invoke-ps2exe -inputFile $wrapperPs1 -outputFile $exeFull -noConsole -title "PAM Shortcut" -description "Generated by PAM Shortcut Launcher"

Remove-Item -LiteralPath $tmpDir -Recurse -Force

Write-Host "OK: $exeFull"


